# Project: wr80emu
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = obj/wr80emu_private.res
OBJ  = obj/wr80emu.o $(RES)
LINKOBJ  = obj/wr80emu.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -static-libgcc  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = bin/wr80emu.exe
CXXFLAGS = $(CXXINCS)   -std=c99
CFLAGS = $(INCS)   -std=c99
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before bin/wr80emu.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "bin\wr80emu.exe" $(LIBS)

obj/wr80emu.o: src/wr80emu.c
	$(CC) -c src/wr80emu.c -o obj/wr80emu.o $(CFLAGS)

obj/wr80emu_private.res: wr80emu_private.rc 
	$(WINDRES) -i wr80emu_private.rc --input-format=rc -o obj/wr80emu_private.res -O coff 
