# Project: wr80lang
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = obj/wr80lang_private.res
OBJ  = obj/wr80lang.o $(RES)
LINKOBJ  = obj/wr80lang.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -static-libgcc -L"C:/Projects/WR80-Dev-Kit/WDK1.8.0/Compilers/WRXLANG/lib" -lassembler  -fmessage-length=0 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = bin/wrx.exe
CXXFLAGS = $(CXXINCS)   -std=c99 -fmessage-length=0
CFLAGS = $(INCS)   -std=c99 -fmessage-length=0
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before bin/wrx.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "bin\wrx.exe" $(LIBS)

obj/wr80lang.o: src/wr80lang.c
	$(CC) -c src/wr80lang.c -o obj/wr80lang.o $(CFLAGS)

obj/wr80lang_private.res: wr80lang_private.rc 
	$(WINDRES) -i wr80lang_private.rc --input-format=rc -o obj/wr80lang_private.res -O coff 
